### ISSUE TITLE
Question à propos des TOS

### ISSUE THREAD

**Issue by hjonin** [codegouvfr/keycloak-theme-dsfr#3]
Est-ce que les TOS [ici](https://github.com/codegouvfr/keycloak-theme-dsfr/blob/6c936e0c3131ea099e5af7f333bf5e9940bbbd2c/public/tos_fr.md) (qui semblent correspondre à ceux du SILL) sont utilisés et sont utilisés tels quels (afin de savoir s'il faut mettre à jour l'adresse du SILL à l'intérieur) ?

**Comment by hjonin** [comment]
Idem pour https://github.com/codegouvfr/keycloak-theme-dsfr/blob/6c936e0c3131ea099e5af7f333bf5e9940bbbd2c/public/index.html

**Comment by bzg** [comment]
A mon avis ce sont simplement des informations qu'il faut nettoyer de `keycloak-theme-dsfr`.

@garronej tu confirmes?

**Comment by garronej** [comment]
@hjonin Yes, pour le title in public oui tu as raison il faut que je vire ça.  

Pour les TOS du SILL, je ne crois pas y faire référence dans le code si ce n'est dans le readme, comme exampte de configuration:  

<img width="921" alt="image" src="https://github.com/codegouvfr/keycloak-theme-dsfr/assets/6702424/db831cd3-0e30-4b05-9db0-4f4ab75ef0a5">

Les gens fournissent la propre terms en environement variable (de manière optionel).  

Ca te gène qu'on utilise les tos du sill comme example?

**Comment by hjonin** [comment]
@garronej pas de problème pour l'utiliser en exemple dans le README !

Ce sont bien les références dans `public/` qu'il semble falloir nettoyer ([`public/tos_fr.md`](https://github.com/codegouvfr/keycloak-theme-dsfr/blob/6c936e0c3131ea099e5af7f333bf5e9940bbbd2c/public/tos_fr.md) et [`public/index.html`](https://github.com/codegouvfr/keycloak-theme-dsfr/blob/6c936e0c3131ea099e5af7f333bf5e9940bbbd2c/public/index.html)).

**Comment by sbourdon13** [comment]
Hello @garronej @hjonin,

J'ai le même problème concernant [public/index.html](https://github.com/codegouvfr/keycloak-theme-dsfr/blob/6c936e0c3131ea099e5af7f333bf5e9940bbbd2c/public/index.html). Dans mon projet, j'ai uniquement récupéré l'archive jar du thème keycloak dsfr et configuré les variables d'environnement fournies en exemple.
Sur ma page de login, j'ai beaucoup de balises du SILL : title, meta et script qui envoie du tracking à Matomo.

Donc quand je copie colle ma page de login dans Teams ou Outlook ça prête à confusion 😬 
![image](https://github.com/codegouvfr/keycloak-theme-dsfr/assets/24961480/1ca0ac9f-9d2e-4b72-bca0-effa1d01e55c)

Et le RSSI nous demande pourquoi on envoie une requête vers une instance matomo/piwik de data.gouv.fr.

Je n'ai pas bien compris comment "nettoyer" ce fichier : l'idée serait de cloner ce repo, enlever les balises HTML qui ne correspondent pas à mon projet et remplacer le title, puis regénérer l'archive du thème grâce à Keycloakify ?

Merci !

**Comment by garronej** [comment]
@sbourdon13 @hjonin, Je viens de nétoyer les balises <meta /> relative au SILL, j'ai aussi enlever le TOS du SILL du dossier publique.  

Une nouvelle version est en train d'être publiée.  

Merci d'avoir reporté!

**Comment by garronej** [comment]
@bzg Ah oui en effet non, je viens de le faire. Une nouvelle version est en cour de publication par le CI.

**Comment by bzg** [comment]
Top, merci !

**Comment by SaraBourdon-Gouv** [comment]
Hello je me rends compte que j'avais oublié de vous remercier pour le correctif super rapide alors merci 🙏
