### ISSUE TITLE
La page "Mot de passe oublié" n'est pas affiché même si le switch est activé dans la config d'un realm.

### ISSUE THREAD

**Issue by HubM** [codegouvfr/keycloak-theme-dsfr#7]
Hello ! 
On est en train d'investiguer pour passer la gestion de l'auth de l'app [Potentiel](https://potentiel.beta.gouv.fr/) aux couleurs dsfr en utilisant le thème dsfr. 

J'ai remarqué que le lien de la page "Mot de passe oublié" n'était pas affiché même si j'ai bien coché "Forgot password" dans [realm] > Realm settings > Login >  Forgot password

Par contre la page s'affiche bien si je coche le switch "User registration"

Je mets des captures d'écrans en PJ pour que ça soit plus explicite
![login-page](https://github.com/codegouvfr/keycloak-theme-dsfr/assets/13203242/42fb97ab-f1d1-48e1-a831-201585bf51f3)
![realm-settings](https://github.com/codegouvfr/keycloak-theme-dsfr/assets/13203242/610430bc-e993-41a6-8cfc-057485d4bf99)

**Comment by garronej** [comment]
@HubM Thanks for reporting, It's fixed in 1.0.1!
